const Data = [
  {
    head: 'Beverly Hills Polo Club',
    title: 'Diamond Patterns Slim Fit Shirt',
    img: require('../assets/images/product.png'),
    price: 'AED 209',
    Delivery: 'Delivery by 16 Sep, Friday',
    id: 1,
  },
  {
    head: 'Beverly Hills Polo Club',
    title: 'Diamond Patterns Slim Fit Shirt',
    price: 'AED 2010',
    Delivery: 'Delivery by 16 Sep, Friday',
    img: require('../assets/images/product.png'),
    id: 2,
  },
  {
    head: 'Beverly Hills Polo Club',
    title: 'Diamond Patterns Slim Fit Shirt',
    price: 'AED 2090',
    Delivery: 'Delivery by 16 Sep, Friday',
    img: require('../assets/images/product.png'),
    id: 3,
  },
  {
    head: 'Beverly Hills Polo Club',
    title: 'Diamond Patterns Slim Fit Shirt',
    price: 'AED 2091',
    Delivery: 'Delivery by 16 Sep, Friday',
    img: require('../assets/images/product.png'),
    id: 4,
  },
  {
    head: 'Beverly Hills Polo Club',
    title: 'Diamond Patterns Slim Fit Shirt',
    price: 'AED 2092',
    Delivery: 'Delivery by 16 Sep, Friday',
    img: require('../assets/images/product.png'),
    id: 5,
  },
  {
    head: 'Beverly Hills Polo Club',
    title: 'Diamond Patterns Slim Fit Shirt',
    price: 'AED 2093',
    Delivery: 'Delivery by 16 Sep, Friday',
    img: require('../assets/images/product.png'),
    id: 6,
  },
];
export default Data;
