export const data = [
  {
    id: '1',
    head: 'Beverly Hills Polo Club',
    title: 'Diamond Patterns Slim Fit Shirt',
    price: 'AED 2090',
    cutprice: '-43% AED 130',
    Delivery: 'Delivery by ',
    Date: '16 Sep, Friday',
    img: require('../assets/images/product.png'),
    isOutOfStock: false,
  },
  {
    id: '2',
    head: 'Beverly Hills Polo Club',
    title: 'Diamond Patterns Slim Fit Shirt',
    price: 'AED 2090',
    cutprice: '-43% AED 130',
    Delivery: 'Delivery by ',
    Date: '16 Sep, Friday',
    img: require('../assets/images/shirts.png'),
    isOutOfStock: false,
  },
  {
    id: '3',
    head: 'Beverly Hills Polo Club',
    title: 'Diamond Patterns Slim Fit Shirt',
    price: 'AED 2090',
    cutprice: '-43% AED 130',
    Delivery: 'Delivery by ',
    Date: '16 Sep, Friday',
    img: require('../assets/images/shirts_1.png'),
    isOutOfStock: false,
  },
];
