export const data = [
  {
    id: '1',
    head: 'Beverly Hills Polo Club',
    title: 'Diamond Patterns Slim Fit Shirt',
    price: 'AED 2090',
    Delivery: 'Delivery by 16 Sep, Friday',
    img: require('../assets/images/product.png'),
  },
  {
    id: '2',
    head: 'Beverly Hills Polo Club',
    title: 'Diamond Patterns Slim Fit Shirt',
    price: 'AED 2090',
    Delivery: 'Delivery by 16 Sep, Friday',
    img: require('../assets/images/shirts.png'),
  },
  {
    id: '3',
    head: 'Beverly Hills Polo Club',
    title: 'Diamond Patterns Slim Fit Shirt',
    price: 'AED 2090',
    Delivery: 'Delivery by 16 Sep, Friday',
    img: require('../assets/images/shirts_1.png'),
  },
  // {
  //   id: '4',
  //   head: 'Beverly Hills Polo Club',
  //   title: 'Diamond Patterns Slim Fit Shirt',
  //   price: 'AED 2090',
  //   Delivery: 'Delivery by 16 Sep, Friday',
  //   img: require('../assets/images/product.png'),
  // },
  // {
  //   id: '5',
  //   head: 'Beverly Hills Polo Club',
  //   title: 'Diamond Patterns Slim Fit Shirt',
  //   price: 'AED 2090',
  //   Delivery: 'Delivery by 16 Sep, Friday',
  //   img: require('../assets/images/product.png'),
  // },
  // {
  //   id: '6',
  //   head: 'Beverly Hills Polo Club',
  //   title: 'Diamond Patterns Slim Fit Shirt',
  //   price: 'AED 2090',
  //   Delivery: 'Delivery by 16 Sep, Friday',
  //   img: require('../assets/images/product.png'),
  // },
  // {
  //   id: '7',
  //   head: 'Beverly Hills Polo Club',
  //   title: 'Diamond Patterns Slim Fit Shirt',
  //   price: 'AED 2090',
  //   Delivery: 'Delivery by 16 Sep, Friday',
  //   img: require('../assets/images/product.png'),
  // },
  // {
  //   id: '8',
  //   head: 'Beverly Hills Polo Club',
  //   title: 'Diamond Patterns Slim Fit Shirt',
  //   price: 'AED 2090',
  //   Delivery: 'Delivery by 16 Sep, Friday',
  //   img: require('../assets/images/product.png'),
  // },
  // {
  //   id: '9',
  //   head: 'Beverly Hills Polo Club',
  //   title: 'Diamond Patterns Slim Fit Shirt',
  //   price: 'AED 2090',
  //   Delivery: 'Delivery by 16 Sep, Friday',
  //   img: require('../assets/images/product.png'),
  // },
  // {
  //   id: '10',
  //   head: 'Beverly Hills Polo Club',
  //   title: 'Diamond Patterns Slim Fit Shirt',
  //   price: 'AED 2090',
  //   Delivery: 'Delivery by 16 Sep, Friday',
  //   img: require('../assets/images/product.png'),
  // },
];
