export const data = [
  {
    id: '1',
    head: 'Beverly Hills Polo Club',
    title: 'Diamond Patterns Slim Fit Shirt',
    price: 'AED 2090',
    Delivery: 'Delivery by 16 Sep, Friday',
    img: require('../assets/images/product.png'),
  },
  {
    id: '2',
    head: 'Beverly Hills Polo Club',
    title: 'Diamond Patterns Slim Fit Shirt',
    price: 'AED 2090',
    Delivery: 'Delivery by 16 Sep, Friday',
    img: require('../assets/images/product.png'),
  },
  {
    id: '3',
    head: 'Beverly Hills Polo Club',
    title: 'Diamond Patterns Slim Fit Shirt',
    price: 'AED 2090',
    Delivery: 'Delivery by 16 Sep, Friday',
    img: require('../assets/images/product.png'),
  },
  {
    id: '4',
    head: 'Beverly Hills Polo Club',
    title: 'Diamond Patterns Slim Fit Shirt',
    price: 'AED 2090',
    Delivery: 'Delivery by 16 Sep, Friday',
    img: require('../assets/images/product.png'),
  },
  {
    id: '5',
    head: 'Beverly Hills Polo Club',
    title: 'Diamond Patterns Slim Fit Shirt',
    price: 'AED 2090',
    Delivery: 'Delivery by 16 Sep, Friday',
    img: require('../assets/images/product.png'),
  },
  {
    id: '6',
    head: 'Beverly Hills Polo Club',
    title: 'Diamond Patterns Slim Fit Shirt',
    price: 'AED 2090',
    Delivery: 'Delivery by 16 Sep, Friday',
    img: require('../assets/images/product.png'),
  },
  {
    id: '7',
    head: 'Beverly Hills Polo Club',
    title: 'Diamond Patterns Slim Fit Shirt',
    price: 'AED 2090',
    Delivery: 'Delivery by 16 Sep, Friday',
    img: require('../assets/images/product.png'),
  },
  {
    id: '8',
    head: 'Beverly Hills Polo Club',
    title: 'Diamond Patterns Slim Fit Shirt',
    price: 'AED 2090',
    Delivery: 'Delivery by 16 Sep, Friday',
    img: require('../assets/images/product.png'),
  },
  {
    id: '9',
    head: 'Beverly Hills Polo Club',
    title: 'Diamond Patterns Slim Fit Shirt',
    price: 'AED 2090',
    Delivery: 'Delivery by 16 Sep, Friday',
    img: require('../assets/images/product.png'),
  },
  {
    id: '10',
    head: 'Beverly Hills Polo Club',
    title: 'Diamond Patterns Slim Fit Shirt',
    price: 'AED 2090',
    Delivery: 'Delivery by 16 Sep, Friday',
    img: require('../assets/images/product.png'),
  },
  //   {id: '11', name: 'K'},
  //   {id: '12', name: 'L'},
  //   {id: '13', name: 'M'},
  //   {id: '14', name: 'N'},
  //   {id: '15', name: 'O'},
  //   {id: '16', name: 'P'},
  //   {id: '17', name: 'Q'},
  //   {id: '18', name: 'R'},
  //   {id: '19', name: 'S'},
  //   {id: '20', name: 'T'},
  //   {id: '21', name: 'U'},
  //   {id: '22', name: 'V'},
  //   {id: '23', name: 'W'},
  //   {id: '24', name: 'X'},
  //   {id: '25', name: 'Y'},
  //   {id: '26', name: 'Z'},
];
